//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1dataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDCAMEntities : DbContext
    {
        public BDCAMEntities()
            : base("name=BDCAMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<alumno> alumno { get; set; }
        public virtual DbSet<programa> programa { get; set; }
        public virtual DbSet<recursos> recursos { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tabla_indicadores_telefono> tabla_indicadores_telefono { get; set; }
        public virtual DbSet<tabla_medica> tabla_medica { get; set; }
        public virtual DbSet<turnos> turnos { get; set; }
        public virtual DbSet<tutor> tutor { get; set; }
        public virtual DbSet<alergias> alergias { get; set; }
        public virtual DbSet<discapacidades> discapacidades { get; set; }
        public virtual DbSet<enfermedades> enfermedades { get; set; }
        public virtual DbSet<telefono_tutores> telefono_tutores { get; set; }
    }
}
