//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1dataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BDCAMEntities1 : DbContext
    {
        public BDCAMEntities1()
            : base("name=BDCAMEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<alumno> alumnoes { get; set; }
        public virtual DbSet<permiso> permisos { get; set; }
        public virtual DbSet<programa> programas { get; set; }
        public virtual DbSet<recurso> recursos { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<subpermiso> subpermisos { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tabla_indicadores_telefono> tabla_indicadores_telefono { get; set; }
        public virtual DbSet<tabla_medica> tabla_medica { get; set; }
        public virtual DbSet<turno> turnos { get; set; }
        public virtual DbSet<tutor> tutors { get; set; }
        public virtual DbSet<usuario> usuarios { get; set; }
        public virtual DbSet<alergia> alergias { get; set; }
        public virtual DbSet<discapacidade> discapacidades { get; set; }
        public virtual DbSet<enfermedade> enfermedades { get; set; }
        public virtual DbSet<rol_tiene_permiso> rol_tiene_permiso { get; set; }
        public virtual DbSet<telefono_tutores> telefono_tutores { get; set; }
    
        public virtual int sp_altaalergias(Nullable<int> id, string alergia)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var alergiaParameter = alergia != null ?
                new ObjectParameter("alergia", alergia) :
                new ObjectParameter("alergia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_altaalergias", idParameter, alergiaParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> SP_AltaAlumno(Nullable<System.DateTime> fecha_registro, string cicloescolar, string nombre, string apellido_pat, string apellido_mat, Nullable<System.DateTime> fecha_nac, string edad_alumno, string curp, string estadonac, string ciudadnac, string colonia, string calle, string numero_alumno, string telefonoper, string escuela, string documentacion, string atendidopor)
        {
            var fecha_registroParameter = fecha_registro.HasValue ?
                new ObjectParameter("fecha_registro", fecha_registro) :
                new ObjectParameter("fecha_registro", typeof(System.DateTime));
    
            var cicloescolarParameter = cicloescolar != null ?
                new ObjectParameter("cicloescolar", cicloescolar) :
                new ObjectParameter("cicloescolar", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var apellido_patParameter = apellido_pat != null ?
                new ObjectParameter("apellido_pat", apellido_pat) :
                new ObjectParameter("apellido_pat", typeof(string));
    
            var apellido_matParameter = apellido_mat != null ?
                new ObjectParameter("apellido_mat", apellido_mat) :
                new ObjectParameter("apellido_mat", typeof(string));
    
            var fecha_nacParameter = fecha_nac.HasValue ?
                new ObjectParameter("fecha_nac", fecha_nac) :
                new ObjectParameter("fecha_nac", typeof(System.DateTime));
    
            var edad_alumnoParameter = edad_alumno != null ?
                new ObjectParameter("edad_alumno", edad_alumno) :
                new ObjectParameter("edad_alumno", typeof(string));
    
            var curpParameter = curp != null ?
                new ObjectParameter("curp", curp) :
                new ObjectParameter("curp", typeof(string));
    
            var estadonacParameter = estadonac != null ?
                new ObjectParameter("estadonac", estadonac) :
                new ObjectParameter("estadonac", typeof(string));
    
            var ciudadnacParameter = ciudadnac != null ?
                new ObjectParameter("ciudadnac", ciudadnac) :
                new ObjectParameter("ciudadnac", typeof(string));
    
            var coloniaParameter = colonia != null ?
                new ObjectParameter("colonia", colonia) :
                new ObjectParameter("colonia", typeof(string));
    
            var calleParameter = calle != null ?
                new ObjectParameter("calle", calle) :
                new ObjectParameter("calle", typeof(string));
    
            var numero_alumnoParameter = numero_alumno != null ?
                new ObjectParameter("numero_alumno", numero_alumno) :
                new ObjectParameter("numero_alumno", typeof(string));
    
            var telefonoperParameter = telefonoper != null ?
                new ObjectParameter("telefonoper", telefonoper) :
                new ObjectParameter("telefonoper", typeof(string));
    
            var escuelaParameter = escuela != null ?
                new ObjectParameter("escuela", escuela) :
                new ObjectParameter("escuela", typeof(string));
    
            var documentacionParameter = documentacion != null ?
                new ObjectParameter("documentacion", documentacion) :
                new ObjectParameter("documentacion", typeof(string));
    
            var atendidoporParameter = atendidopor != null ?
                new ObjectParameter("atendidopor", atendidopor) :
                new ObjectParameter("atendidopor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("SP_AltaAlumno", fecha_registroParameter, cicloescolarParameter, nombreParameter, apellido_patParameter, apellido_matParameter, fecha_nacParameter, edad_alumnoParameter, curpParameter, estadonacParameter, ciudadnacParameter, coloniaParameter, calleParameter, numero_alumnoParameter, telefonoperParameter, escuelaParameter, documentacionParameter, atendidoporParameter);
        }
    
        public virtual int sp_altaalumnocartilla(Nullable<int> id_al, Nullable<int> id_car)
        {
            var id_alParameter = id_al.HasValue ?
                new ObjectParameter("id_al", id_al) :
                new ObjectParameter("id_al", typeof(int));
    
            var id_carParameter = id_car.HasValue ?
                new ObjectParameter("id_car", id_car) :
                new ObjectParameter("id_car", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_altaalumnocartilla", id_alParameter, id_carParameter);
        }
    
        public virtual int sp_altacartilla(string servicio, string grupo, string telefono, string peso, string genero, string color_textura, string estatura)
        {
            var servicioParameter = servicio != null ?
                new ObjectParameter("servicio", servicio) :
                new ObjectParameter("servicio", typeof(string));
    
            var grupoParameter = grupo != null ?
                new ObjectParameter("grupo", grupo) :
                new ObjectParameter("grupo", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("telefono", telefono) :
                new ObjectParameter("telefono", typeof(string));
    
            var pesoParameter = peso != null ?
                new ObjectParameter("peso", peso) :
                new ObjectParameter("peso", typeof(string));
    
            var generoParameter = genero != null ?
                new ObjectParameter("genero", genero) :
                new ObjectParameter("genero", typeof(string));
    
            var color_texturaParameter = color_textura != null ?
                new ObjectParameter("color_textura", color_textura) :
                new ObjectParameter("color_textura", typeof(string));
    
            var estaturaParameter = estatura != null ?
                new ObjectParameter("estatura", estatura) :
                new ObjectParameter("estatura", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_altacartilla", servicioParameter, grupoParameter, telefonoParameter, pesoParameter, generoParameter, color_texturaParameter, estaturaParameter);
        }
    
        public virtual int sp_altadiscapacidades(Nullable<int> id_car, string dis)
        {
            var id_carParameter = id_car.HasValue ?
                new ObjectParameter("id_car", id_car) :
                new ObjectParameter("id_car", typeof(int));
    
            var disParameter = dis != null ?
                new ObjectParameter("dis", dis) :
                new ObjectParameter("dis", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_altadiscapacidades", id_carParameter, disParameter);
        }
    
        public virtual int sp_altaenfermedades(Nullable<int> id_car, string enf)
        {
            var id_carParameter = id_car.HasValue ?
                new ObjectParameter("id_car", id_car) :
                new ObjectParameter("id_car", typeof(int));
    
            var enfParameter = enf != null ?
                new ObjectParameter("enf", enf) :
                new ObjectParameter("enf", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_altaenfermedades", id_carParameter, enfParameter);
        }
    
        public virtual int sp_altatutor(string nombre, string apellidopat, string apellidomat, string colonia, string calle, string numero, string ocupacion, string coloniatrabajo, string calletrabajo, string numerotrabajo)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var apellidopatParameter = apellidopat != null ?
                new ObjectParameter("apellidopat", apellidopat) :
                new ObjectParameter("apellidopat", typeof(string));
    
            var apellidomatParameter = apellidomat != null ?
                new ObjectParameter("apellidomat", apellidomat) :
                new ObjectParameter("apellidomat", typeof(string));
    
            var coloniaParameter = colonia != null ?
                new ObjectParameter("colonia", colonia) :
                new ObjectParameter("colonia", typeof(string));
    
            var calleParameter = calle != null ?
                new ObjectParameter("calle", calle) :
                new ObjectParameter("calle", typeof(string));
    
            var numeroParameter = numero != null ?
                new ObjectParameter("numero", numero) :
                new ObjectParameter("numero", typeof(string));
    
            var ocupacionParameter = ocupacion != null ?
                new ObjectParameter("ocupacion", ocupacion) :
                new ObjectParameter("ocupacion", typeof(string));
    
            var coloniatrabajoParameter = coloniatrabajo != null ?
                new ObjectParameter("coloniatrabajo", coloniatrabajo) :
                new ObjectParameter("coloniatrabajo", typeof(string));
    
            var calletrabajoParameter = calletrabajo != null ?
                new ObjectParameter("calletrabajo", calletrabajo) :
                new ObjectParameter("calletrabajo", typeof(string));
    
            var numerotrabajoParameter = numerotrabajo != null ?
                new ObjectParameter("numerotrabajo", numerotrabajo) :
                new ObjectParameter("numerotrabajo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_altatutor", nombreParameter, apellidopatParameter, apellidomatParameter, coloniaParameter, calleParameter, numeroParameter, ocupacionParameter, coloniatrabajoParameter, calletrabajoParameter, numerotrabajoParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<SP_FichaTecnicaAlumno_Result> SP_FichaTecnicaAlumno(Nullable<int> id_alumno)
        {
            var id_alumnoParameter = id_alumno.HasValue ?
                new ObjectParameter("id_alumno", id_alumno) :
                new ObjectParameter("id_alumno", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_FichaTecnicaAlumno_Result>("SP_FichaTecnicaAlumno", id_alumnoParameter);
        }
    
        public virtual ObjectResult<SP_FichaTecnicaAlumnoMedica_Result> SP_FichaTecnicaAlumnoMedica(Nullable<int> id_alumno)
        {
            var id_alumnoParameter = id_alumno.HasValue ?
                new ObjectParameter("id_alumno", id_alumno) :
                new ObjectParameter("id_alumno", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_FichaTecnicaAlumnoMedica_Result>("SP_FichaTecnicaAlumnoMedica", id_alumnoParameter);
        }
    
        public virtual ObjectResult<SP_FichaTecnicaAlumnoTutor_Result> SP_FichaTecnicaAlumnoTutor(Nullable<int> id_alumno)
        {
            var id_alumnoParameter = id_alumno.HasValue ?
                new ObjectParameter("id_alumno", id_alumno) :
                new ObjectParameter("id_alumno", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_FichaTecnicaAlumnoTutor_Result>("SP_FichaTecnicaAlumnoTutor", id_alumnoParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<SP_ListaAlergia_Result> SP_ListaAlergia(Nullable<int> id_alumno)
        {
            var id_alumnoParameter = id_alumno.HasValue ?
                new ObjectParameter("id_alumno", id_alumno) :
                new ObjectParameter("id_alumno", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ListaAlergia_Result>("SP_ListaAlergia", id_alumnoParameter);
        }
    
        public virtual ObjectResult<SP_ListaAlumnos_Result> SP_ListaAlumnos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ListaAlumnos_Result>("SP_ListaAlumnos");
        }
    
        public virtual ObjectResult<SP_ListaDiscapacidad_Result> SP_ListaDiscapacidad(Nullable<int> id_alumno)
        {
            var id_alumnoParameter = id_alumno.HasValue ?
                new ObjectParameter("id_alumno", id_alumno) :
                new ObjectParameter("id_alumno", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ListaDiscapacidad_Result>("SP_ListaDiscapacidad", id_alumnoParameter);
        }
    
        public virtual ObjectResult<SP_ListaEnfermedad_Result> SP_ListaEnfermedad(Nullable<int> id_alumno)
        {
            var id_alumnoParameter = id_alumno.HasValue ?
                new ObjectParameter("id_alumno", id_alumno) :
                new ObjectParameter("id_alumno", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ListaEnfermedad_Result>("SP_ListaEnfermedad", id_alumnoParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> sp_regresarid()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("sp_regresarid");
        }
    
        public virtual ObjectResult<Nullable<decimal>> sp_regresaridcartilla()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("sp_regresaridcartilla");
        }
    
        public virtual ObjectResult<Nullable<decimal>> sp_regresaridtutor()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("sp_regresaridtutor");
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_telefonotutores(Nullable<int> idtutor, Nullable<int> idtelefono, string telefono)
        {
            var idtutorParameter = idtutor.HasValue ?
                new ObjectParameter("idtutor", idtutor) :
                new ObjectParameter("idtutor", typeof(int));
    
            var idtelefonoParameter = idtelefono.HasValue ?
                new ObjectParameter("idtelefono", idtelefono) :
                new ObjectParameter("idtelefono", typeof(int));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("telefono", telefono) :
                new ObjectParameter("telefono", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_telefonotutores", idtutorParameter, idtelefonoParameter, telefonoParameter);
        }
    
        public virtual int sp_tutoralumno(Nullable<int> id_alumno, Nullable<int> id_tutor)
        {
            var id_alumnoParameter = id_alumno.HasValue ?
                new ObjectParameter("id_alumno", id_alumno) :
                new ObjectParameter("id_alumno", typeof(int));
    
            var id_tutorParameter = id_tutor.HasValue ?
                new ObjectParameter("id_tutor", id_tutor) :
                new ObjectParameter("id_tutor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tutoralumno", id_alumnoParameter, id_tutorParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
