//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1dataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDCAMEntities : DbContext
    {
        public BDCAMEntities()
            : base("name=BDCAMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<alumno> alumno { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tabla_indicadores_telefono> tabla_indicadores_telefono { get; set; }
        public virtual DbSet<tabla_medica> tabla_medica { get; set; }
        public virtual DbSet<tutor> tutor { get; set; }
        public virtual DbSet<alergias> alergias { get; set; }
        public virtual DbSet<discapacidades> discapacidades { get; set; }
        public virtual DbSet<enfermedades> enfermedades { get; set; }
        public virtual DbSet<telefono_tutores> telefono_tutores { get; set; }
    }
}
