//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1dataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class discapacidades
    {
        public int id_cartilla_medica { get; set; }
        public string discapacidades1 { get; set; }
        public int id_discapacidades { get; set; }
    
        public virtual tabla_medica tabla_medica { get; set; }
    }
}
