//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1dataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabla_medica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tabla_medica()
        {
            this.alumno = new HashSet<alumno>();
            this.Tratamientos = new HashSet<Tratamientos>();
            this.catalogo_alergia = new HashSet<catalogo_alergia>();
            this.catalogo_discapacidades = new HashSet<catalogo_discapacidades>();
            this.catalogo_enfermedades = new HashSet<catalogo_enfermedades>();
        }
    
        public int id_cartilla_medica { get; set; }
        public string servicio_medico { get; set; }
        public string grupo_sanguineo { get; set; }
        public string telefono_contacto { get; set; }
        public string peso { get; set; }
        public string genero { get; set; }
        public string color_textura_piel { get; set; }
        public string estatura { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<alumno> alumno { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tratamientos> Tratamientos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalogo_alergia> catalogo_alergia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalogo_discapacidades> catalogo_discapacidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalogo_enfermedades> catalogo_enfermedades { get; set; }
    }
}
