//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1dataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabla_medica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tabla_medica()
        {
            this.alergias = new HashSet<alergia>();
            this.discapacidades = new HashSet<discapacidade>();
            this.enfermedades = new HashSet<enfermedade>();
            this.alumnoes = new HashSet<alumno>();
        }
    
        public int id_cartilla_medica { get; set; }
        public string servicio_medico { get; set; }
        public string grupo_sanguineo { get; set; }
        public string telefono_contacto { get; set; }
        public string peso { get; set; }
        public string genero { get; set; }
        public string color_textura_piel { get; set; }
        public string estatura { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<alergia> alergias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<discapacidade> discapacidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enfermedade> enfermedades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<alumno> alumnoes { get; set; }
    }
}
