//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1dataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class telefono_tutores
    {
        public int id_tutor { get; set; }
        public int id_telefono { get; set; }
        public string telefono { get; set; }
    
        public virtual tabla_indicadores_telefono tabla_indicadores_telefono { get; set; }
        public virtual tutor tutor { get; set; }
    }
}
